<script>
    function placeOrder() {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log("Order placed..!");
                resolve('');
            }, 2000);
        });
    }

    function makePayment() {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log("Payment done..!");
                resolve('');
                //reject('Not enough balance..!');
            }, 3000);
        });
    }

    function confirmOrder() {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log("Order confirmed..!");
                resolve('');
            },1000);
        });
    }

    function sendMail() {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                //console.log("mail sent..!");
               // resolve('');
               reject('Email template not found..!')
            }, 3000);
        });
    }

  function processingOrder() {
    console.log("Processing started..!");
    placeOrder()
    .then(()=> makePayment())
    .then(() => confirmOrder())
    .then(() => sendMail())
    .then(() => console.log('Order placed process ended..!'))
    .catch((msg) => console.log("Error message:", msg));
  }
  processingOrder();

//   try{
//     processingOrder();
//   }
//   catch { //catch block only handle errors not the rejections
//     console.log("Some error occured and handled..!");
//   }
</script>